import Navbar from '@/Component/Navbar'
import './globals.scss'
import Footer from '@/Component/Footer'
import Providers from '@/Providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='px-1 md:px-14 mx-auto max-w-[1500px]'>
        <Providers>
          <Navbar />
          <main className='min-h-screen'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
